M48
; DRILL file {KiCad (6.0.6)} date Sat Jan 28 17:15:24 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-28T17:15:24-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.861
%
G90
G05
T1
X77.5Y-69.5
X77.5Y-120.0
X171.5Y-69.5
X171.5Y-120.0
T0
M30
